# Generated by Django 3.2.16 on 2022-11-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0001_squashed_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixuseridentity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
