# Generated by Django 3.2.16 on 2022-11-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0002_alter_matrixuseridentity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixuseridentity',
            name='paging_room',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='matrixuseridentity',
            name='user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
