# Generated by Django 3.2.16 on 2022-11-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0003_auto_20221117_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixuseridentity',
            name='paging_room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matrixuseridentity',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
