# Generated by Django 3.2.16 on 2022-11-19 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0004_auto_20221117_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matrixuseridentity',
            old_name='paging_room',
            new_name='paging_room_id',
        ),
    ]
